### ISSUE TITLE
Add URL & Description

### ISSUE THREAD

**Issue by connorads** [merykozlowska/bunnies#1]
Marketing and that init, make it look pretterierer
![image](https://user-images.githubusercontent.com/10026538/172178332-e07a3119-28ea-4158-add9-553bb2ed96db.png)
![image](https://user-images.githubusercontent.com/10026538/172178462-80245e0d-5d8d-4418-b29c-85b8e46cff2c.png)

**Comment by adrienbaron** [comment]
Fixed by @merykozlowska ✨

<img width="307" alt="image" src="https://user-images.githubusercontent.com/4410247/172873002-c8f16bcb-86a1-4d4e-8474-4d265294261e.png">
